Added VERY basic reactjs ui stuff
pandabear15/equidistant pull request #14
Opened 2023-02-08 04:50 UTC by adundarov

I added a pages folder in SRC with some pages and their respective css. I also modified some files like app.tsx and index.tsx to add navigation. I also updated package.json dependencies

2023-02-08 04:55 UTC, adundarov commented
I see the issue, strangely didn't go off on my machine but the app.tsx changes seem to be not working well with the tests. Will fix shortly

2023-02-08 09:12 UTC, jspaniac approved these changes
Wow, nice! Lgtm!

2023-02-08 23:04 UTC, zshafe approved these changes
Overall looks good for a basic draft of UI stuff, but we'll want to do a lot of refactoring as soon as we have a MVP for the Beta version. Additionally, just curious about the use of basic HTML tags and straight CSS as opposed to using a component library. I also recommend (if you haven't seen it already) using the [new Beta React Documentation](https://beta.reactjs.org/) if you haven't seen them before. While technically still in Beta, they are 99% done at this point and have the most up to date style and tools. There's tons of outdated React things out there, so just wanted to be sure you knew about these

2023-02-08 23:04 UTC, zshafe commented on package-lock.json
> +  "name": "equidistant",
I don't think that this needs to exist. The relevant package-lock.json is in the `my-app` directory, and this is empty anyway

2023-02-08 23:04 UTC, zshafe commented on frontend/my-app/src/Pages/Account.css
> +    display: flex;
While building out our own `.css` files and whatnot is great, I am curious if this was necessary, as yesterday we talked about using `material-ui`'s pre-styled components. Is that something you want to get into after the beta release?

2023-02-08 23:04 UTC, zshafe commented on frontend/my-app/src/Pages/Account.tsx
> +        <div className="right-column">
This feels like a lot of things that we could (and should) break down into multiple components, but for the purposes of getting a beta version out it looks good

2023-02-08 23:05 UTC, zshafe requested changes
just drop the top level package-lock and i'm good w/ merging for now

2023-02-09 21:39 UTC, zshafe approved these changes
ship it

2023-02-09 21:39 UTC, merged