Landing page UI/main
pandabear15/equidistant pull request #25
Opened 2023-02-12 08:34 UTC by adundarov

2023-02-12 22:42 UTC, jspaniac commented
There are some errors in the console regarding
"MUI: You are providing an onClick event listener to a child of a button element."
We could push it for the demo and open an issue or we could try and fix it now. I'll go ahead and start investigating later tonight

2023-02-12 22:58 UTC, jspaniac approved these changes
LGTM! I went ahead and fixed the console errors I was seeing and also added in a quick fix for some issues in the results page (back button & wrap around)

2023-02-13 20:38 UTC, zshafe requested changes
just some style that would be nice to clean up but otherwise LGTM

2023-02-13 20:38 UTC, zshafe commented on frontend/my-app/src/Pages/LandingPage.tsx
> +              <Button color='secondary' variant='contained' onClick={handleLogoutClick}>Logout</Button>
NIT: I would prefer if some of the style here was cleaned up. For example:
```
<Button color='secondary' variant='contained' onClick={handleLogoutClick}>Logout</Button>
```
should look like
```
<Button
     color='secondary'
     variant='contained'
     onClick={handleLogoutClick}>
          Logout
</Button>
```

2023-02-13 20:38 UTC, zshafe commented on frontend/my-app/src/Pages/LandingPage.tsx
> +                      opacity: [0.8, 0.8, 0.8]
Is there a way to condense these styling aspects to something smaller and resuable?

2023-02-13 20:57 UTC, zshafe approved these changes

2023-02-13 20:59 UTC, merged